// <auto-generated />
using System;
using E_Commerce_Backend.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce_Backend.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce_Backend.Entity.AllProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("AllProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "men's clothing",
                            Description = "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
                            Image = "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
                            Price = 109.95m,
                            Title = "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops"
                        },
                        new
                        {
                            Id = 2,
                            Category = "men's clothing",
                            Description = "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
                            Image = "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
                            Price = 22.3m,
                            Title = "Mens Casual Premium Slim Fit T-Shirts"
                        },
                        new
                        {
                            Id = 3,
                            Category = "men's clothing",
                            Description = "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
                            Image = "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
                            Price = 55.99m,
                            Title = "Mens Cotton Jacket"
                        },
                        new
                        {
                            Id = 4,
                            Category = "men's clothing",
                            Description = "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
                            Image = "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
                            Price = 15.99m,
                            Title = "Mens Casual Slim Fit"
                        },
                        new
                        {
                            Id = 5,
                            Category = "jewelery",
                            Description = "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
                            Image = "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
                            Price = 695m,
                            Title = "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet"
                        },
                        new
                        {
                            Id = 6,
                            Category = "jewelery",
                            Description = "Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.",
                            Image = "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
                            Price = 168m,
                            Title = "Solid Gold Petite Micropave"
                        },
                        new
                        {
                            Id = 7,
                            Category = "jewelery",
                            Description = "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
                            Image = "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
                            Price = 9.99m,
                            Title = "White Gold Plated Princess"
                        },
                        new
                        {
                            Id = 8,
                            Category = "jewelery",
                            Description = "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
                            Image = "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
                            Price = 10.99m,
                            Title = "Pierced Owl Rose Gold Plated Stainless Steel Double"
                        },
                        new
                        {
                            Id = 9,
                            Category = "electronics",
                            Description = "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system",
                            Image = "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
                            Price = 64m,
                            Title = "WD 2TB Elements Portable External Hard Drive - USB 3.0"
                        },
                        new
                        {
                            Id = 10,
                            Category = "electronics",
                            Description = "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
                            Image = "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
                            Price = 109m,
                            Title = "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s"
                        },
                        new
                        {
                            Id = 11,
                            Category = "electronics",
                            Description = "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
                            Image = "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
                            Price = 109m,
                            Title = "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5"
                        },
                        new
                        {
                            Id = 12,
                            Category = "electronics",
                            Description = "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
                            Image = "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
                            Price = 114m,
                            Title = "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive"
                        },
                        new
                        {
                            Id = 13,
                            Category = "electronics",
                            Description = "21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz",
                            Image = "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
                            Price = 599m,
                            Title = "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin"
                        },
                        new
                        {
                            Id = 14,
                            Category = "electronics",
                            Description = "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag",
                            Image = "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
                            Price = 999.99m,
                            Title = "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED"
                        },
                        new
                        {
                            Id = 15,
                            Category = "women's clothing",
                            Description = "Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates",
                            Image = "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
                            Price = 56.99m,
                            Title = "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats"
                        },
                        new
                        {
                            Id = 16,
                            Category = "women's clothing",
                            Description = "100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON",
                            Image = "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
                            Price = 29.95m,
                            Title = "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket"
                        },
                        new
                        {
                            Id = 17,
                            Category = "women's clothing",
                            Description = "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
                            Image = "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
                            Price = 39.99m,
                            Title = "Rain Jacket Women Windbreaker Striped Climbing Raincoats"
                        },
                        new
                        {
                            Id = 18,
                            Category = "women's clothing",
                            Description = "95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem",
                            Image = "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
                            Price = 9.85m,
                            Title = "MBJ Women's Solid Short Sleeve Boat Neck V"
                        },
                        new
                        {
                            Id = 19,
                            Category = "women's clothing",
                            Description = "100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
                            Image = "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
                            Price = 7.95m,
                            Title = "Opna Women's Short Sleeve Moisture"
                        },
                        new
                        {
                            Id = 20,
                            Category = "women's clothing",
                            Description = "95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.",
                            Image = "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
                            Price = 12.99m,
                            Title = "DANVOUY Womens T Shirt Casual Cotton Short"
                        });
                });

            modelBuilder.Entity("E_Commerce_Backend.Entity.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("E_Commerce_Backend.Entity.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AllProductId");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("E_Commerce_Backend.Entity.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CartId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("E_Commerce_Backend.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordResetGuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetGuidCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PasswordResetGuidExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("E_Commerce_Backend.Entity.AllProduct", b =>
                {
                    b.OwnsOne("E_Commerce_Backend.Entity.Rating", "Rating", b1 =>
                        {
                            b1.Property<int>("AllProductId")
                                .HasColumnType("int");

                            b1.Property<int>("Count")
                                .HasColumnType("int");

                            b1.Property<decimal>("Rate")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.HasKey("AllProductId");

                            b1.ToTable("AllProducts");

                            b1.WithOwner()
                                .HasForeignKey("AllProductId");

                            b1.HasData(
                                new
                                {
                                    AllProductId = 1,
                                    Count = 120,
                                    Rate = 3.9m
                                },
                                new
                                {
                                    AllProductId = 2,
                                    Count = 259,
                                    Rate = 4.1m
                                },
                                new
                                {
                                    AllProductId = 3,
                                    Count = 500,
                                    Rate = 4.7m
                                },
                                new
                                {
                                    AllProductId = 4,
                                    Count = 430,
                                    Rate = 2.1m
                                },
                                new
                                {
                                    AllProductId = 5,
                                    Count = 400,
                                    Rate = 4.6m
                                },
                                new
                                {
                                    AllProductId = 6,
                                    Count = 70,
                                    Rate = 3.9m
                                },
                                new
                                {
                                    AllProductId = 7,
                                    Count = 400,
                                    Rate = 3m
                                },
                                new
                                {
                                    AllProductId = 8,
                                    Count = 100,
                                    Rate = 1.9m
                                },
                                new
                                {
                                    AllProductId = 9,
                                    Count = 203,
                                    Rate = 3.3m
                                },
                                new
                                {
                                    AllProductId = 10,
                                    Count = 470,
                                    Rate = 2.9m
                                },
                                new
                                {
                                    AllProductId = 11,
                                    Count = 319,
                                    Rate = 4.8m
                                },
                                new
                                {
                                    AllProductId = 12,
                                    Count = 400,
                                    Rate = 4.8m
                                },
                                new
                                {
                                    AllProductId = 13,
                                    Count = 250,
                                    Rate = 2.9m
                                },
                                new
                                {
                                    AllProductId = 14,
                                    Count = 140,
                                    Rate = 2.2m
                                },
                                new
                                {
                                    AllProductId = 15,
                                    Count = 235,
                                    Rate = 2.6m
                                },
                                new
                                {
                                    AllProductId = 16,
                                    Count = 340,
                                    Rate = 2.9m
                                },
                                new
                                {
                                    AllProductId = 17,
                                    Count = 679,
                                    Rate = 3.8m
                                },
                                new
                                {
                                    AllProductId = 18,
                                    Count = 130,
                                    Rate = 4.7m
                                },
                                new
                                {
                                    AllProductId = 19,
                                    Count = 146,
                                    Rate = 4.5m
                                },
                                new
                                {
                                    AllProductId = 20,
                                    Count = 145,
                                    Rate = 3.6m
                                });
                        });

                    b.Navigation("Rating")
                        .IsRequired();
                });

            modelBuilder.Entity("E_Commerce_Backend.Entity.Cart", b =>
                {
                    b.HasOne("E_Commerce_Backend.Entity.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("E_Commerce_Backend.Entity.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Commerce_Backend.Entity.CartItem", b =>
                {
                    b.HasOne("E_Commerce_Backend.Entity.AllProduct", "AllProduct")
                        .WithMany("CartItems")
                        .HasForeignKey("AllProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Commerce_Backend.Entity.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_Backend.Entity.Order", "Order")
                        .WithMany("CartItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AllProduct");

                    b.Navigation("Cart");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("E_Commerce_Backend.Entity.Order", b =>
                {
                    b.HasOne("E_Commerce_Backend.Entity.Cart", "Cart")
                        .WithOne("Order")
                        .HasForeignKey("E_Commerce_Backend.Entity.Order", "CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Commerce_Backend.Entity.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Commerce_Backend.Entity.AllProduct", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("E_Commerce_Backend.Entity.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("E_Commerce_Backend.Entity.Order", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("E_Commerce_Backend.Entity.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
